[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn web_app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 4"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
